/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "s21_matrix_test.check" instead.
 */

#include <check.h>

#include <stdlib.h>
#include <stdio.h>
#include "s21_matrix.h"

START_TEST(create_matrix_test)
{

int rows = 3;
int cols = 4;
matrix_t m;
int res = s21_create_matrix(rows, cols, &m);
printf("Res: %d\n", res);
s21_remove_matrix(&m);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, create_matrix_test);

    srunner_set_fork_status(sr, CK_NOFORK);srunner_run_all(sr, CK_NORMAL);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
